name: create-release-upload

on: 
  push:
    tags:
    - 'v*'

jobs:
  create_releases:
    name: create-releases
    runs-on: ubuntu-24.04

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Get the version
      id: get_version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      shell: bash
    - name: check package.json version
      env:
        version: ${{ steps.get_version.outputs.VERSION }}
      run: python ./tools/version_checker.py ${version}
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ steps.get_version.outputs.VERSION }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        prerelease: true
      continue-on-error: true

  upload-sdist:
    name: upload-sdist
    needs: create_releases
    timeout-minutes: 20
    runs-on: ubuntu-24.04

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: create sdist
      id: create_sdist
      run: python setup.py sdist --formats=gztar,zip
    - name: Upload sdist
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./dist/*.tar.gz
          ./dist/*.zip

  upload-wheel:
    name: upload-wheel
    needs: create_releases
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-14, windows-2019, ubuntu-20.04]
        include:
          - os: macos-13
            py-ver: 3.9
            pl-name: macosx_13_0_x86_64
          - os: macos-14
            py-ver: 3.9
            pl-name: macosx_14_0_arm64
          - os: ubuntu-20.04
            py-ver: 3.9
            pl-name: linux_x86_64
          - os: windows-2019
            py-ver: 3.9
            pl-name: win_amd64

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py-ver }}
    - name: Get the version
      id: get_version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      shell: bash
    - name: Get the asset name
      id: asset_name
      run: echo "ASSET_NAME=cfd-${{ steps.get_version.outputs.VERSION }}-py3-none-${{ matrix.pl-name }}.whl" >> $GITHUB_OUTPUT
      shell: bash
    - name: install pip & wheel
      run: |
        python -m pip install -U pip
        pip install wheel
    - name: create wheel
      id: create_wheel
      run: |
        pip wheel .
        WHEEL_NAME=$(ls *.whl)
        mv $WHEEL_NAME ${{ steps.asset_name.outputs.ASSET_NAME }}
      shell: bash
    - name: Upload wheel
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ steps.asset_name.outputs.ASSET_NAME }}
